const U = require('../lib/util');
const crypto = require('crypto');
const INDEX='articles/index.json';
function config(){const {GITHUB_TOKEN:token,GITHUB_OWNER:owner,GITHUB_REPO:repo}=process.env;if(!token||!owner||!repo)throw Error('Hãy cấu hình GitHub để lưu bài báo');return {token,owner,repo,branch:process.env.GITHUB_BRANCH||'main'}}
const pathPart=p=>p.split('/').map(encodeURIComponent).join('/');
async function github(path,method='GET',body){const c=config(),r=await fetch(`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/${path}`,{method,headers:{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok){const e=Error(j.message||`GitHub lỗi ${r.status}`);e.status=r.status;throw e}return j}
async function read(){try{const j=await github(`contents/${INDEX}?ref=${encodeURIComponent(config().branch)}`);return {sha:j.sha,items:JSON.parse(Buffer.from(j.content,'base64').toString('utf8'))}}catch(e){if(e.status===404)return {items:[]};throw e}}
async function write(items,sha){await github(`contents/${INDEX}`,'PUT',{message:'Update articles',branch:config().branch,content:Buffer.from(JSON.stringify(items,null,2)).toString('base64'),...(sha?{sha}:{})})}
const statuses=['Đang chuẩn bị','Đã gửi','Đang phản biện','Đã chấp nhận','Đã xuất bản','Từ chối'],ranks=['Chưa phân loại','Q1','Q2','Q3','Q4'];
function clean(b,old){const i={id:old?.id||crypto.randomUUID(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};for(const f of ['title','authors','venue','year','page','issn','doi','abstract','status','scopus','wos','language','code','repository','requirements','notes','references','blocks'])i[f]=String(b[f]||'').trim();if(['-','—',''].includes(i.wos))i.wos='Chưa phân loại';if(!i.title||i.title.length>1000)throw Error('Tiêu đề bắt buộc, tối đa 1000 ký tự');if(!/^\d{4}$/.test(i.year)||+i.year<1900||+i.year>2200)throw Error('Năm không hợp lệ');if(!statuses.includes(i.status)||!ranks.includes(i.scopus)||!['Chưa phân loại','SCIE','SSCI','AHCI','ESCI',...ranks.slice(1)].includes(i.wos))throw Error('Phân loại không hợp lệ');if(JSON.stringify(i).length>1000000)throw Error('Nội dung quá lớn');const keep=new Set(Array.isArray(b.keepFiles)?b.keepFiles:(old?.files||[]).map(f=>f.id));i.files=(old?.files||[]).filter(f=>keep.has(f.id));return i}
module.exports=U.h(async(req,res)=>{const user=U.user(req);if(!user)return res.status(401).json({error:'Chưa đăng nhập'});const act=req.query.act,index=await read(),items=index.items,b=req.body||{},old=items.find(i=>i.id===b.id);
if(req.method==='GET'){if(act!=='file')return res.json({items});const f=items.flatMap(i=>i.files||[]).find(f=>f.id===req.query.id);if(!f)return res.status(404).json({error:'Không tìm thấy tệp'});const c=config(),r=await fetch(`https://api.github.com/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}/contents/${pathPart(f.path)}?ref=${encodeURIComponent(c.branch)}`,{headers:{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github.raw'}});if(!r.ok)return res.status(r.status).json({error:'Không tải được tệp'});const inline=req.query.inline==='1'&&['image/png','image/jpeg','image/gif','image/webp'].includes(f.type);res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Type',inline?f.type:'application/octet-stream');res.setHeader('Content-Disposition',`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name).replace(/'/g,'%27')}`);return res.send(Buffer.from(await r.arrayBuffer()))}
if(req.method!=='POST')return res.status(405).json({error:'Phương thức không được hỗ trợ'});
if(act==='save'||act==='import'){let added;try{if(act==='save'&&b.id&&!old)return res.status(404).json({error:'Không tìm thấy bài báo'});const rows=act==='import'?b.items:[b];if(!Array.isArray(rows)||!rows.length||rows.length>500)throw Error('Mỗi lần nhập từ 1 đến 500 bài báo');added=rows.map(r=>clean(r,act==='save'?old:null))}catch(e){return res.status(400).json({error:e.message})}const next=old&&act==='save'?items.map(i=>i.id===old.id?added[0]:i):[...added,...items];await write(next,index.sha);return res.json({items:next,id:added[0].id})}
if(!old)return res.status(404).json({error:'Không tìm thấy bài báo'});
if(act==='delete'){const next=items.filter(i=>i.id!==old.id);await write(next,index.sha);return res.json({items:next})}
if(act==='upload'){const {uploadId,chunk,count,data}=b;if(!/^[a-f0-9-]{36}$/.test(uploadId||'')||!Number.isInteger(chunk)||!Number.isInteger(count)||count<1||count>14||chunk<0||chunk>=count||typeof data!=='string'||data.length>2800000||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(data))return res.status(400).json({error:'Phần tệp không hợp lệ'});const key=`article-upload:${user}:${b.id}:${uploadId}`;let upload=await U.get(key);if(!upload)upload={parts:[],count,name:String(b.name||'tep').split(/[\\/]/).pop().replace(/[\u0000-\u001f]/g,'').slice(0,180),type:['image/png','image/jpeg','image/gif','image/webp'].includes(b.type)?b.type:'application/octet-stream',role:['evidence','code','note'].includes(b.role)?b.role:'evidence'};if(upload.count!==count)return res.status(400).json({error:'Số phần tệp không khớp'});upload.parts[chunk]=data;await U.set(key,upload);await U.rd('EXPIRE',key,3600);if(Array.from({length:count},(_,i)=>upload.parts[i]).some(p=>typeof p!=='string'))return res.json({pending:true});const bytes=Buffer.concat(upload.parts.map(p=>Buffer.from(p,'base64')));if(bytes.length>20*1024*1024)return res.status(413).json({error:'Mỗi tệp tối đa 20 MB'});const latest=await read(),target=latest.items.find(i=>i.id===b.id);if(!target)return res.status(404).json({error:'Bài báo đã bị xóa'});if(!(target.files||[]).some(f=>f.id===uploadId)){const path=`articles/files/${b.id}/${uploadId}/${upload.name}`;try{await github(`contents/${pathPart(path)}`,'PUT',{message:'Add article attachment',branch:config().branch,content:bytes.toString('base64')})}catch(e){if(e.status!==422)throw e;const existing=await github(`contents/${pathPart(path)}?ref=${encodeURIComponent(config().branch)}`);if(existing.size!==bytes.length)throw e}target.files=[...(target.files||[]),{id:uploadId,name:upload.name,role:upload.role,type:upload.type,path,size:bytes.length}];await write(latest.items,latest.sha)}await U.rd('DEL',key);return res.json({items:latest.items})}
return res.status(400).json({error:'Thao tác không hợp lệ'})});
